'use client';

import LegalPageLayout from '@/components/LegalPageLayout';

export default function CookiePolicy() {
  return (
    <LegalPageLayout title="Cookie Policy" lastUpdated="July 12, 2026">
      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">1. What Are Cookies?</h2>
        <p>
          Cookies are small text files stored on your computer or mobile device by websites you visit. 
          They are widely used to make websites function, improve loading efficiency, and provide basic profile tracking parameters.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">2. Cookies We Use</h2>
        <p>
          Resence Fitness maintains a highly privacy-centric cookie policy. We only use cookies that are strictly necessary to deliver our services.
        </p>
        <ul className="list-disc pl-5 space-y-2 text-zinc-400">
          <li>
            <strong>Essential Authentication Cookies</strong>: 
            Supabase auth tokens (e.g. `sb-access-token` and `sb-refresh-token`) are used to securely verify your credentials, keeping you logged into your fitness dashboard as you switch between logs.
          </li>
          <li>
            <strong>Session Verification</strong>: 
            Temporary system cookies generated by our hosting infrastructure to identify active sessions.
          </li>
          <li>
            <strong>No Tracker/Marketing Cookies</strong>: 
            We do not use advertising, marketing, or tracking pixels (such as Meta pixel, Google Ads retargeting, etc.). Your activities are never tracked across other sites.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">3. How to Manage Cookies</h2>
        <p>
          Most web browsers allow you to block or delete cookies through browser settings. 
          To adjust your cookie preferences, consult your browser's documentation (e.g., Settings &gt; Privacy &gt; Cookies). 
          Please note that disabling cookies will prevent you from signing in or maintaining an active account session on Resence.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">4. Cookie Consent Banner</h2>
        <p>
          Upon your first visit, a cookie consent banner is displayed at the bottom of the landing page requesting your acknowledgement. 
          By clicking "Accept", you acknowledge our use of essential authentication cookies to manage your fitness dashboard session.
        </p>
      </section>
    </LegalPageLayout>
  );
}
