'use client';

import LegalPageLayout from '@/components/LegalPageLayout';

export default function TermsOfService() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="July 12, 2026">
      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">1. Acceptance of Terms</h2>
        <p>
          By creating an account, logging in, or interacting with the Resence Fitness client, you agree to comply with and be bound by these Terms of Service. 
          If you do not agree, please discontinue using our software platforms.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">2. Service Description & Medical Disclaimer</h2>
        <p>
          Resence is an automated fitness portal that translates user parameters into workout layouts and nutrient estimations.
        </p>
        <div className="p-4 bg-orange-950/20 border border-orange-900 text-orange-400 text-xs rounded-xl leading-relaxed">
          <strong>⚠️ IMPORTANT NOTICE</strong>: All suggestions, exercises, splits, sets, and caloric estimates compiled by our AI models (specifically the Google Gemini model series) are for informational purposes only. 
          They do NOT constitute medical advice, diagnosis, treatment, or professional physical therapy advice. 
          Physical exercise carries risk of injury.
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">3. User Responsibilities & Registration</h2>
        <p>
          To maintain a safe and productive environment, you agree that:
        </p>
        <ul className="list-disc pl-5 space-y-1 text-zinc-400">
          <li>You are at least 18 years of age.</li>
          <li>You will consult a qualified medical professional (doctor or physiotherapist) before starting any training plan generated by the AI, particularly if you have injuries or medical conditions.</li>
          <li>You will input accurate profile statistics (weight, height, goals) to prevent the AI from generating inappropriate routine volumes.</li>
          <li>You will not use the platform for any illegal activities or to harvest network tokens.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">4. Account Termination</h2>
        <p>
          We reserve the right to suspend, terminate, or remove user profiles at our discretion without prior notice if we detect misuse, database abuse, or violations of these terms. 
          You may request profile deletion at any time via settings or by email.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">5. Limitation of Liability</h2>
        <p>
          Resence Fitness, its authors, and AI service providers shall not be held liable for any damages, muscle strains, physical injuries, cardiovascular incidents, or metabolic issues resulting from following AI-generated workout routines or nutrition advice. 
          Your reliance on the AI coach suggestions is entirely at your own risk.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">6. Governing Law</h2>
        <p>
          These terms and agreements shall be governed by, construed, and enforced in accordance with local regulations, without giving effect to conflicts of law principles.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-white font-bold text-lg border-l-2 border-orange-500 pl-3">7. Free Service Disclaimer</h2>
        <p>
          Resence Fitness is provided on an "as-is" and "as-available" basis at no cost. 
          We make no warranties of merchantability or fitness for a particular purpose. 
          We reserve the right to modify, adapt, limit, or discontinue any features, dashboard tools, or AI models at any time without liability.
        </p>
      </section>
    </LegalPageLayout>
  );
}
